### ISSUE TITLE
in general, file.path should be used to create paths, not paste0

### ISSUE THREAD

**Issue by wStockhausen** [GMACS-project/gmr#12]
For consistency in general, file.path should (almost) always be used to create paths, not paste0. paste0 is used to create file paths in .GetGmacsExe.R (which I'm revising on my level-buck branch). Will keep an eye out for other usages.

**Comment by MatthVeron** [comment]
That's right. This is a mistake on my part. I will correct this in the next versions. Thanks for correcting the existing ones in the .GetGmacsExe.R and in the other functions
